classDiagram
  class ListProxyBuilder {
    TIMEOUT : int
  }
  class ProxyBuilder {
    request_timeout : Optional[int]
    url : Optional[str]
    get_proxies() list[str]
  }
  class ProxyHandler {
    PROXY_MAX_USES : int
    lock : lock
    proxy_builders : list, list[ProxyBuilder]
    proxy_list : list, list[str]
    proxy_max_uses : int
    proxy_uses : dict
    get_next_proxy() Union[str, None]
  }
  class RequestHandler {
    PARALLEL_WORKERS : int
    jobs_queue : Queue
    num_workers : int
    workers : list[RequestWorker]
    do_request(job: RequestJob)
    do_requests(request_jobs: list[RequestJob], num_workers: int, progress_bar: tqdm.tqdm)
  }
  class RequestJob {
    FINALIZE_KEY : str
    key : object
    params : Optional[dict[str, str]]
    response : Response
    url : str
    end_job_signal() RequestJob
    set_response(job_response: requests.Response)
  }
  class RequestWorker {
    RETRIES : int
    RETRY_DELAY : int
    TIMEOUT : int
    jobs_queue : Queue
    my_jobs : list
    progress_bar : tqdm
    proxy_handler
    stopped : bool
    user_agent_handler
    worker_id : int
    run()
  }
  class SSLProxiesBuilder {
  }
  class UserAgentHandler {
    DATA_FILE
    DATA_FILE : str
    USERAGENTSTRING_URL : str
    lock : lock
    useragents_list : list
    useragents_list : list[str]
    get_next_useragent() str
  }
  ListProxyBuilder --|> ProxyBuilder
  SSLProxiesBuilder --|> ProxyBuilder
  ProxyHandler --* RequestWorker : proxy_handler
  UserAgentHandler --* RequestWorker : user_agent_handler
