classDiagram
  class Package {
    dependencies : list, List[Package]
    name : str
    url : Optional[str]
    version : Optional[str]
    get_dependencies() List[Package]
    get_dependencies_names() List[str]
    load(data: dict)
    print()
    to_dict()
    update(data: dict)
  }
