classDiagram
  class data_source {
  }
  class csv_ds {
  }
  class data_source {
  }
  class librariesio_ds {
  }
  class repository_scrapers {
  }
  class bioconductor {
  }
  class cran {
  }
  class github {
  }
  class npm {
  }
  class pypi {
  }
  class r {
  }
  class scraper_ds {
  }
  csv_ds --> data_source
  librariesio_ds --> data_source
  scraper_ds --> data_source
